# Generated by Django 6.0.1 on 2026-01-27 10:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('product_code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='รหัสสินค้า')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพ')),
                ('product_format', models.CharField(blank=True, max_length=100, null=True, verbose_name='รูปแบบสินค้า')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='หมวดหมู่สินค้า')),
                ('current_stock', models.IntegerField(default=0, verbose_name='สินค้าคงเหลือ')),
                ('min_limit', models.IntegerField(default=0, verbose_name='Min Limit')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='POHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='เลข PO')),
                ('order_type', models.CharField(choices=[('IMPORTED', 'Imported'), ('DOMESTIC', 'Domestic')], max_length=20, verbose_name='ประเภทรายการ')),
                ('shipping_type', models.CharField(blank=True, choices=[('CAR', 'Car'), ('SHIP', 'Ship')], max_length=20, null=True, verbose_name='ขนส่ง')),
                ('order_date', models.DateField(verbose_name='วันที่สั่งซื้อ')),
                ('estimated_date', models.DateField(blank=True, null=True, verbose_name='วันคาดการณ์')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='เรทเงิน')),
                ('total_yuan', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดหยวน (¥)')),
                ('shipping_cost_baht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ต้นทุน/ชิ้น (฿)')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Pending', max_length=20, verbose_name='สถานะ')),
            ],
        ),
        migrations.CreateModel(
            name='JSTStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='คงเหลือ')),
                ('jst_min_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('raw_type', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.masteritem')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.IntegerField(verbose_name='สั่งซื้อ')),
                ('price_yuan', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดหยวน (¥)')),
                ('price_baht', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดบาทรวม (฿)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='CBM')),
                ('total_received_qty', models.IntegerField(default=0, verbose_name='รับแล้ว')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.poheader')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.masteritem', verbose_name='รหัสสินค้า')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_qty', models.IntegerField(verbose_name='จำนวนที่รับ')),
                ('received_date', models.DateField(default=datetime.date.today, verbose_name='วันที่รับ')),
                ('received_cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='inventory.poitem')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order ID')),
                ('qty', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('platform', models.CharField(choices=[('Shopee', 'Shopee'), ('Lazada', 'Lazada'), ('TikTok', 'TikTok')], max_length=50, verbose_name='Platform')),
                ('date', models.DateField(verbose_name='Date')),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shop Name')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('voucher_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.masteritem', verbose_name='SKU')),
            ],
            options={
                'unique_together': {('order_id', 'sku')},
            },
        ),
    ]
