# Generated by Django 6.0.1 on 2026-01-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poheader',
            name='lazada_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาขาย Lazada'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='link_shop',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ลิงค์ร้านค้า'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='shopee_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาขาย Shopee'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='tiktok_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาขาย TikTok'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='wechat_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WeChat / ติดต่อ'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='น้ำหนัก (KG)'),
        ),
        migrations.CreateModel(
            name='POAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='po_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.poheader')),
            ],
        ),
    ]
