# Generated by Django 6.0.1 on 2026-01-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_poheader_lazada_price_poheader_link_shop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('master', 'Master Data'), ('stock', 'Stock JST'), ('sales', 'Sales History')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
