# Generated by Django 6.0.1 on 2026-01-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_importlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='total_received_cbm',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='รับแล้ว (CBM)'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='total_received_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='รับแล้ว (Weight)'),
        ),
        migrations.AddField(
            model_name='receivedpoitem',
            name='received_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='น้ำหนักที่รับ'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='total_received_qty',
            field=models.IntegerField(default=0, verbose_name='รับแล้ว (จำนวน)'),
        ),
        migrations.AlterField(
            model_name='receivedpoitem',
            name='received_cbm',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='CBM ที่รับ'),
        ),
        migrations.AlterField(
            model_name='receivedpoitem',
            name='received_qty',
            field=models.IntegerField(default=0, verbose_name='จำนวนที่รับ'),
        ),
    ]
