# Generated by Django 6.0.1 on 2026-01-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_poitem_total_received_cbm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteritem',
            name='lazada_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาขาย Lazada'),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='shopee_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาขาย Shopee'),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='tiktok_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาขาย TikTok'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='shipping_rate_cbm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าส่ง/CBM'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='shipping_rate_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าส่ง/กก.'),
        ),
    ]
