# Generated by Django 6.0.1 on 2026-01-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_masteritem_lazada_price_masteritem_shopee_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitem',
            name='height',
        ),
        migrations.RemoveField(
            model_name='poitem',
            name='length',
        ),
        migrations.RemoveField(
            model_name='poitem',
            name='width',
        ),
        migrations.AddField(
            model_name='poheader',
            name='shipping_rate_yuan_per_cbm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าส่ง/CBM (หยวน)'),
        ),
        migrations.AlterField(
            model_name='poheader',
            name='shipping_rate_cbm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าส่ง/CBM (บาท)'),
        ),
    ]
