# Generated by Django 6.0.1 on 2026-02-03 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_poitem_height_remove_poitem_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poheader',
            name='lazada_price',
        ),
        migrations.RemoveField(
            model_name='poheader',
            name='shipping_cost_baht',
        ),
        migrations.RemoveField(
            model_name='poheader',
            name='shipping_rate_cbm',
        ),
        migrations.RemoveField(
            model_name='poheader',
            name='shipping_rate_kg',
        ),
        migrations.RemoveField(
            model_name='poheader',
            name='shipping_rate_yuan_per_cbm',
        ),
        migrations.RemoveField(
            model_name='poheader',
            name='shopee_price',
        ),
        migrations.RemoveField(
            model_name='poheader',
            name='tiktok_price',
        ),
        migrations.RemoveField(
            model_name='poitem',
            name='cbm',
        ),
        migrations.RemoveField(
            model_name='poitem',
            name='weight',
        ),
        migrations.AddField(
            model_name='poheader',
            name='ref_price_lazada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคา Lazada (Ref)'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='ref_price_shopee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคา Shopee (Ref)'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='ref_price_tiktok',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคา TikTok (Ref)'),
        ),
        migrations.AddField(
            model_name='poheader',
            name='shipping_rate_thb_cbm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='เรทค่าขนส่ง THB/คิว'),
        ),
        migrations.AddField(
            model_name='receivedpoitem',
            name='bill_date',
            field=models.DateField(default=datetime.date.today, verbose_name='วันที่บิล'),
        ),
        migrations.AlterField(
            model_name='poheader',
            name='status',
            field=models.CharField(choices=[('Pending', 'Waiting for Shipment (สินค้ารอจัดส่ง)'), ('Arriving Soon', 'Arriving Soon (สินค้าใกล้ถึง)'), ('Overdue', 'Overdue (เลยกำหนดจัดส่ง)'), ('Incomplete', 'Incomplete (สินค้าไม่ครบ)'), ('Complete', 'Complete (เรียบร้อย)')], default='Pending', max_length=50, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='poheader',
            name='total_yuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดหยวนรวม (Input)'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='price_baht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Baht'),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='price_yuan',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Total Yuan (Prorated)'),
        ),
    ]
