# Generated by Django 6.0.1 on 2026-02-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_poheader_lazada_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poheader',
            name='bill_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่บิลเรียกเก็บ'),
        ),
    ]
