# Generated by Django 6.0.1 on 2026-02-03 11:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_poheader_bill_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='POReceiptBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField(default=1, verbose_name='ครั้งที่')),
                ('bill_date', models.DateField(default=datetime.date.today, verbose_name='วันที่บิล')),
                ('received_date', models.DateField(default=datetime.date.today, verbose_name='วันที่รับ')),
                ('total_cbm', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='รวม CBM (Batch)')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='รวม KG (Batch)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_batches', to='inventory.poheader')),
            ],
            options={
                'ordering': ['batch_no'],
            },
        ),
        migrations.AddField(
            model_name='receivedpoitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.poreceiptbatch'),
        ),
    ]
