# Generated by Django 6.0.1 on 2026-02-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_poreceiptbatch_receivedpoitem_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivedpoitem',
            options={'ordering': ['received_date', 'id']},
        ),
        migrations.AddField(
            model_name='poheader',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=5, verbose_name='VAT %'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ราคาต่อหน่วย'),
        ),
    ]
