# Generated by Django 6.0.1 on 2026-02-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_receivedpoitem_options_poheader_vat_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteritem',
            name='is_favourite',
            field=models.BooleanField(default=False, verbose_name='รายการโปรด'),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='note1',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ 1'),
        ),
        migrations.AddField(
            model_name='masteritem',
            name='note2',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ 2'),
        ),
    ]
