# Generated by Django 6.0.1 on 2026-02-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_masteritem_is_favourite_masteritem_note1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteritem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active (ขายปกติ)'), ('DISCONTINUED', 'Discontinued (เลิกขาย)')], default='ACTIVE', max_length=20, verbose_name='สถานะสินค้า'),
        ),
    ]
