# Generated by Django 6.0.1 on 2026-03-21 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_masteritem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_manual', models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัส/ชื่อสินค้า (กรอกเอง)')),
                ('store_name', models.CharField(max_length=255, verbose_name='ชื่อร้านค้า')),
                ('store_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='ลิงก์ร้านค้า')),
                ('product_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='ลิงก์สินค้า')),
                ('wechat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='WECHAT')),
                ('order_channel', models.CharField(blank=True, max_length=255, null=True, verbose_name='ช่องทางสั่งซื้อ')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='suppliers/products/', verbose_name='รูปสินค้า')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='suppliers/qr/', verbose_name='QR CODE')),
                ('other_image', models.ImageField(blank=True, null=True, upload_to='suppliers/others/', verbose_name='รูปอื่นๆ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.masteritem', verbose_name='สินค้าในระบบ')),
            ],
        ),
    ]
