# Generated by Django 6.0.1 on 2026-05-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_supplierinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poheader',
            name='yuan_mode',
            field=models.CharField(choices=[('top-down', 'Top-down (Prorate)'), ('bottom-up', 'Bottom-up (Manual)')], default='top-down', max_length=20, verbose_name='โหมดราคาหยวน'),
        ),
    ]
